<a href="https://colab.research.google.com/github/Yogesh1108/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


# **One Dimension Array**

In [6]:
b=np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [14]:
b.ndim
print(b,"this is for array")
a.ndim
print(a,'this is for arange')

[1 2 3 4 5] this is for array
[0 1 2 3 4 5 6 7 8] this is for arange


In [18]:
b.shape

(5,)

In [19]:
len(b)

5

# **Two Dimension Array**

In [20]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [21]:
c.ndim 

2

In [22]:
len(c)

2

In [24]:
c.shape

(2, 3)

# **Three Dimension Array**

In [25]:
d=np.array([[[1,2,3],[4,5,6]]])
print(d)

[[[1 2 3]
  [4 5 6]]]


In [26]:
d.ndim

3

In [27]:
d.shape

(1, 2, 3)

# **Array Function**

In [29]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b=np.arange(1,10,2)# 1-10 no. and with two diffrence
b

array([1, 3, 5, 7, 9])

In [32]:
c=np.linspace(5,10,8)# 5-10 no. and with 8 outcome
c

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

In [34]:
d=np.linspace(1,4,7)
d

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [36]:
e=np.ones((3,4)) #Common One Arrays filled with once
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
e=np.zeros((3,3)) # Zero Array filled with zero
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
y=np.eye(4) #Create the identity matrix
y

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
y=np.eye(2,4)
print(y)
y.ndim

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


2

In [44]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [48]:
a=np.random.rand(6)# Give the random no. of the array
a

array([0.21967475, 0.12664288, 0.36595513, 0.3450458 , 0.3186537 ,
       0.71326102])

In [57]:
b=np.array([True,False,True])
b

array([ True, False,  True])

In [59]:
b.dtype

dtype('bool')

# **Indexing and Slicing**

In [61]:
a=np.arange(10)
print(a[6])
print(a[-2])


6
8


In [65]:
a=np.arange(10)
print(a[1:10:2])

[1 3 5 7 9]


In [66]:
b=np.arange(10)
b[5:]=10
print(b)

[ 0  1  2  3  4 10 10 10 10 10]


# **Copies and Views**

In [67]:
a=np.arange(10)
b=a[::2]
np.shares_memory(a,b)

True

In [69]:
b[0]=10 #if we modify the b as well as a also get modify
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [70]:
c=a[::2]
np.shares_memory(a,c)

True

In [71]:
c=a[::2].copy()
np.shares_memory(a,c)

False

In [72]:
c[0]=5
print(c)
print(a)

[5 2 4 6 8]
[10  1  2  3  4  5  6  7  8  9]


# **Fancy Indexing**

In [77]:
a=np.random.randint(1,20,15)
a

array([ 6,  3, 11, 15,  8, 18, 10,  2,  9, 14,  8, 15, 19, 18, 14])

In [78]:
mask=(a%2==0) # creates a Boolean mask indicating whether each element in the array a is even (divisible by 2) or not.
print(mask)

[ True False False False  True  True  True  True False  True  True False
 False  True  True]


In [79]:
a[mask]=1  #mask is boolean array 
a

array([ 1,  3, 11, 15,  1,  1,  1,  1,  9,  1,  1, 15, 19,  1,  1])

# **Element with Wish Operations**

In [81]:
a=np.arange(10)
print(a)
print(a+1)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [83]:
b=np.ones(10)+1
print('b=',b)
print('a-b=',a-b)

b= [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
a-b= [-2. -1.  0.  1.  2.  3.  4.  5.  6.  7.]


In [84]:
print(a*b)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [86]:
c=np.diag([1,4,2])
c.dot(c)

array([[ 1,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  4]])

# **Logical Operators**

In [88]:
a=np.array([1,0,0,1],dtype="bool")
b=np.array([0,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True False  True]


# **Transendental Function **

In [90]:
a=np.arange(5)+1
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [91]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [92]:
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# **Shape Mismatch**

In [93]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [95]:
#Basic Reduction
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [104]:
print(y.sum(axis=0))
print(y.sum(axis=1))
print(y.min())
print(y.max())
print(y.argmin())
print(y.argmax())
print(np.any([True,False,False]))


[1. 1. 0. 0.]
[1. 1.]
0.0
1.0
1
0
True


In [108]:
a=np.zeros([50,50])
np.any(a==0)

True

In [107]:
a=np.zeros([50,50])
np.any(a!=0)

False

# **Statistics**

In [110]:
x=np.arange(1,10)
np.mean(x)

5.0

In [111]:
np.median(x)

5.0

In [113]:
y=np.array([[1,2,3],[4,5,6]])
print(np.mean(y,axis=0))
print(np.median(y,axis=1))
print(np.std(x))

[2.5 3.5 4.5]
[2. 5.]
2.581988897471611


# **Flatting **

In [114]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
print(a.ravel())#ravel mean converting multimidension array into one diamension array
print(a.T)   # T is use for transpose of the matrix

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


# **Reshaping**

In [118]:
print(a.shape)

(2, 3)


In [119]:
b=a.ravel()
print(b.shape)

(6,)


In [120]:
b=b.reshape(2,3)
print(b.shape)

(2, 3)


# **Adding New Dimension**

In [121]:
z=np.arange(1,7,2)
z

array([1, 3, 5])

In [122]:
z=z[:,np.newaxis]
print(z.shape)

(3, 1)


# **Resize**

In [124]:
a=np.arange(5)
a.resize((10))
print(a)

[0 1 2 3 4 0 0 0 0 0]


In [125]:
a=np.array([[5,6,7],[3,4,5]])
a

array([[5, 6, 7],
       [3, 4, 5]])

In [127]:
b=np.sort(a,axis=1)
b

array([[5, 6, 7],
       [3, 4, 5]])

In [128]:
d=a.ravel()
d

array([5, 6, 7, 3, 4, 5])